// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEknRmzvr-3EdM2SiDqas7B-sq5hOk_AU',
    appId: '1:213053993402:web:05834005c1cb2b97602d83',
    messagingSenderId: '213053993402',
    projectId: 'fir-flutter-6ba30',
    authDomain: 'fir-flutter-6ba30.firebaseapp.com',
    storageBucket: 'fir-flutter-6ba30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE7NMFLCJpLuk0_SdcWwpx_zt4eF9sJbY',
    appId: '1:213053993402:android:352cb4d334facc52602d83',
    messagingSenderId: '213053993402',
    projectId: 'fir-flutter-6ba30',
    storageBucket: 'fir-flutter-6ba30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrov_HGsJ2T06sr4e9xeZgugmlwKICcNA',
    appId: '1:213053993402:ios:16900fde906ebc93602d83',
    messagingSenderId: '213053993402',
    projectId: 'fir-flutter-6ba30',
    storageBucket: 'fir-flutter-6ba30.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrov_HGsJ2T06sr4e9xeZgugmlwKICcNA',
    appId: '1:213053993402:ios:16900fde906ebc93602d83',
    messagingSenderId: '213053993402',
    projectId: 'fir-flutter-6ba30',
    storageBucket: 'fir-flutter-6ba30.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEknRmzvr-3EdM2SiDqas7B-sq5hOk_AU',
    appId: '1:213053993402:web:958f6a1f608927df602d83',
    messagingSenderId: '213053993402',
    projectId: 'fir-flutter-6ba30',
    authDomain: 'fir-flutter-6ba30.firebaseapp.com',
    storageBucket: 'fir-flutter-6ba30.appspot.com',
  );
}
